### ISSUE TITLE
No init(bound:) drop in api

### ISSUE THREAD

**Issue by jcampbell05** [shaps80/GraphicsRenderer#2]
This is currently missing the  init(bound:) drop in api

**Comment by shaps80** [comment]
I'll check it out... thanks.

**Comment by shaps80** [comment]
What exactly are you referencing here? As far as I can see there is definitely `init(bounds:)` included. Especially considering none of these APIs would really work without bounds ;)

**Comment by shaps80** [comment]
Apologies -- I see what you mean. I've added it now. Will be in the next release. Thanks.
